# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: '3'

vars:
  RUN: msys2 -no-start -here -mingw64 -shell bash -c

tasks:
  default:
    cmds:
      - task: build

  build:
    deps: [prepare]
    sources:
      - Makefile
    generates:
      - mutt
    cmds:
      - task: run
        vars: { CMD: make }
      
  prepare:
    deps: [packages]
    sources:
      - Makefile.am
    generates:
      - Makefile
      - missing
    cmds:
      - task: run
        vars: { CMD: ./prepare }
            
  packages:
    cmds:
      - task: run
        vars:
          CMD: |
            pacman -S --needed --yes \
              base-devel msys2-devel \
              libgpgme-devel libsasl-devel libgdbm-devel \
              ncurses-devel libgnutls-devel libidn-devel \
              openssl-devel

  build-release:
    aliases: [release]
    sources:
      - Makefile.am
    generates:
      - Makefile
      - missing
    cmds:
      - task: run
        vars: { CMD: ./build-release }

  run:
    requires:
      vars: [CMD]
    cmds:
      - cmd: >-
          {{.RUN}} "{{.CMD}}"
